name: Build VoltageOS 16.2 (Tetris)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the build config
        uses: actions/checkout@v4

      - name: Cleanup Space
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /usr/local/lib/android
          sudo apt-get clean

      - name: Setup Repo & Git
        run: |
          mkdir ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          git config --global user.name "valt-x"
          git config --global user.email "valtaoi@example.com"

      - name: Sync Manifest
        env:
          MY_KEY: ${{ secrets.GH_TOKEN }}
        run: |
          export PATH=$PATH:$HOME/bin
          # Initialize the master manifest
          repo init -u https://x-access-token:$MY_KEY@github.com/mucache/manifest.git -b 16.2
          
          # Copy the CMF Phone 1 "Shopping List Add-on"
          mkdir -p .repo/local_manifests
          cp roomservice.xml .repo/local_manifests/tetris.xml
          
          # Sync the 150GB
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build ROM
        run: |
          source build/envsetup.sh
          lunch lineage_Tetris-userdebug
          mka bacon -j$(nproc --all)

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: VoltageOS-16.2-Tetris
          path: out/target/product/Tetris/VoltageOS*.zip
